### ISSUE TITLE
不会加载数据

### ISSUE THREAD

**Issue by ahjsrhj** [darkerk/v2ex#1]
刚刚下载体验了一下，打开App没有弹出是否允许访问网络，手动刷新也没有任何数据出来，进入手机设置查看使用蜂窝数据与无线局域网的软件，列表里没有这款。

**Comment by darkerk** [comment]
@ahjsrhj 删掉重新下载一下试试也不可以么，你的设置里一直没有这个？
![screen shot 2017-04-28 at 9 45 03](https://cloud.githubusercontent.com/assets/1670251/25511177/dc377f10-2bf7-11e7-8186-4604f4a8b161.png)

**Comment by ahjsrhj** [comment]
重新安装之后打开有提示允许使用网络了，但是确认之后刷新还是没有数据，杀掉之后重新打开才能加载。
建议优化一下~

**Comment by ahjsrhj** [comment]
刚发现一个bug,切到二手交易节点，进入主题详情刷新不出来评论，因为我还没有登录，建议加个提示啥的

**Comment by darkerk** [comment]
@ahjsrhj 详情页面评论目前是UITextView处理的，性能还是可以看出有很大影响，准备换其他方案来处理评论富文本

**Comment by ahjsrhj** [comment]
@darkerk 我的意思是，v站上二手交易节点的主题必须要登录之后才能查看详情，在app里面如果没有登录是无法加载详情页面的，所以我看别的app一般会弹个登录啥的

**Comment by darkerk** [comment]
@ahjsrhj 嗯，这个已经修复。目前其他地方像评论、收藏、感谢等等操作，如果没有登录就不会展示这些操作，想想还是放出来比较好，用户点击提示登录就可以了。
