### ISSUE TITLE
viewdidload是完全没用到吗？

### ISSUE THREAD

**Issue by asasdasasd** [darkerk/v2ex#5]
https://github.com/darkerk/v2ex/blob/master/V2EX/ViewControllers/DrawerViewController.swift#L72

**Comment by darkerk** [comment]
有执行的，不然你都打不开左边的dramer

**Comment by asasdasasd** [comment]
开始打断点不执行，后来全注释了也没影响啊

**Comment by asasdasasd** [comment]
左边的drawer不是和上边的willset有关么

**Comment by asasdasasd** [comment]
@darkerk

**Comment by darkerk** [comment]
willset里不处理手势的，你的疑问应该是panGesture.rx.event.subscribe这里打个断点为什么不执行，这里panGesture声明时加上了lazy，你把lazy去掉，这里的断点就会执行了。

**Comment by asasdasasd** [comment]
尴尬了，模拟器上只点了点，没注意到是个手势:joy:
